name: flutter_application
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.2.3
  google_maps_flutter_web: ^0.5.0
  intl: ^0.19.0
  table_calendar: ^3.0.9

  # Consumo de APIs y seguridad
  dio: ^5.0.0
  http: ^0.13.5
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0
  jwt_decoder: ^2.0.1

  # Utilidades
  fluttertoast: ^8.2.2
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  qr_flutter: ^4.1.0
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_charts: ^29.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
